export const UI_DESIGN_TOKENS = {
  colour: {
    ink: '#4f3a5d',
    softInk: '#6f5a79',
    mutedInk: '#8d7193',
    cream: '#fffbef',
    creamText: '#fffaf1',
    parchment: '#fff4dc',
    parchmentStrong: '#f1ddbc',
    lavender: '#ead8f3',
    lavenderStrong: '#c192d5',
    lavenderDark: '#76518a',
    ribbon: '#d9b5e7',
    ribbonStrong: '#b97dcc',
    gold: '#ffe6a6',
    goldStrong: '#d6b35f',
    blush: '#ffdbe8',
    blushStrong: '#e99ab7',
    mint: '#dff1df',
    mintStrong: '#90c89a',
    focus: '#7d5a92',
    shadow: '#4b3658',
    white: '#ffffff',
    conceptPurple: '#b96ae8',
    conceptPurpleLight: '#d89af4',
    conceptPurpleStrong: '#8a48bd',
    conceptPurpleDeep: '#5c2d82',
    conceptLavenderLine: '#c99be0',
    conceptGold: '#ffc85c',
    conceptGoldLight: '#ffe69e',
    conceptGoldStrong: '#c98527',
    conceptGoldDeep: '#7d4f20',
    conceptBlue: '#8dd5ec',
    conceptBlueLight: '#dff6fd',
    conceptBlueStrong: '#4f9fc4',
    conceptBlueDeep: '#244f5c',
    conceptInk: '#4b2b66',
    conceptSoftInk: '#6b4a78',
    conceptShadow: '#2f1d43',
  },
  typography: {
    family: 'Trebuchet MS, Segoe UI, system-ui, sans-serif',
    bodyPx: 18,
    captionPx: 17,
    weightStrong: 700,
  },
  radius: {
    controlPx: 16,
    rowPx: 22,
    panelPx: 30,
    pillPx: 999,
  },
  border: {
    controlPx: 3,
    strongPx: 4,
    panelPx: 6,
  },
  shadow: {
    offsetXPx: 6,
    offsetYPx: 7,
  },
  spacing: {
    xsPx: 8,
    smPx: 12,
    mdPx: 16,
    lgPx: 24,
    xlPx: 32,
  },
  control: {
    minimumTouchTargetPx: 48,
    nativeHeightPx: 44,
  },
  depth: {
    canvasBase: 1,
    canvasPanel: 2,
    canvasList: 5,
    canvasControl: 6,
    canvasLabel: 7,
    canvasGuard: 20,
    canvasChrome: 24,
    domOverlay: 30,
  },
  viewport: {
    logicalWidth: 1280,
    logicalHeight: 720,
  },
} as const;

export function cssColourToPhaser(value: string): number {
  return Number.parseInt(value.slice(1), 16);
}
