export const CLICK_NAVIGATION_SUPPORTED_SCENES = [
  'MoonflowerGladeScene',
  'SunbeamVillageScene',
  'RainbowMeadowScene',
  'CrystalBrookScene',
  'WhisperingWoodsScene',
  'StarlightBeachScene',
  'CottageInteriorScene',
  'MoonflowerPatchScene',
  'HollowTreeNookScene',
  'WindmillLookoutScene',
  'CrystalGrottoScene',
  'FireflyGroveScene',
] as const;

export const CLICK_NAVIGATION_SCENE_CLASSIFICATION = {
  supported: CLICK_NAVIGATION_SUPPORTED_SCENES,
  intentionallyStatic: [
    'TitleScene',
    'UnicornCreatorScene',
    'InventoryScene',
    'WonderbookScene',
    'SettingsScene',
    'CottageDecorateScene',
    'ShopScene',
    'VillageInteriorScene',
    'R6VillageInteriorScene',
    'DoorwayStubScene',
    'PipEggHatchScene',
    'RainbowRunEntryScene',
    'NovaTutorialRaceScene',
    'RaceScene',
    'FireflyLanternScene',
  ],
} as const;
