import { createHash } from 'node:crypto';
import { promises as fs } from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const AUDIO_ROOT = path.join(ROOT, 'public', 'audio');
const OUTPUT = path.join(ROOT, 'src', 'generated', 'audioCatalogue.ts');
const CHECK_ONLY = process.argv.includes('--check');

function toPosix(value) {
  return value.split(path.sep).join('/');
}

function makeId(kind, relativePath) {
  const withoutExtension = relativePath.replace(/\.mp3$/i, '');
  const slug = withoutExtension
    .toLowerCase()
    .replace(/[^a-z0-9/]+/g, '-')
    .replace(/(^-|-$)/g, '');
  return `${kind}:${slug}`;
}

function makeLabel(relativePath) {
  const base = path.basename(relativePath, path.extname(relativePath));
  return base
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, (character) => character.toUpperCase());
}

async function walk(directory) {
  let entries;
  try {
    entries = await fs.readdir(directory, { withFileTypes: true });
  } catch (error) {
    if (error?.code === 'ENOENT') {
      return [];
    }
    throw error;
  }

  const files = [];
  for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name))) {
    const absolutePath = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await walk(absolutePath)));
    } else if (entry.isFile() && entry.name.toLowerCase().endsWith('.mp3')) {
      files.push(absolutePath);
    }
  }
  return files;
}

function looksLikeMp3(buffer) {
  if (buffer.length < 3) {
    return false;
  }
  if (buffer.subarray(0, 3).toString('ascii') === 'ID3') {
    return true;
  }
  return buffer.length >= 2 && buffer[0] === 0xff && (buffer[1] & 0xe0) === 0xe0;
}

async function discover(kind) {
  const root = path.join(AUDIO_ROOT, kind);
  const files = await walk(root);
  return Promise.all(
    files.map(async (absolutePath) => {
      const relativePath = toPosix(path.relative(root, absolutePath));
      const publicPath = `/audio/${kind}/${relativePath}`;
      const buffer = await fs.readFile(absolutePath);
      if (!looksLikeMp3(buffer)) {
        throw new Error(`Audio catalogue rejected ${publicPath}: file does not look like MP3 audio.`);
      }
      return {
        id: makeId(kind, relativePath),
        kind,
        path: publicPath,
        relativePath,
        filename: path.basename(relativePath),
        label: makeLabel(relativePath),
        bytes: buffer.length,
        sha256: createHash('sha256').update(buffer).digest('hex'),
      };
    }),
  );
}

function render(entries) {
  const body = entries
    .map(
      (entry) => `  ${JSON.stringify(entry, null, 2).replace(/\n/g, '\n  ')},`,
    )
    .join('\n');

  return `// This file is generated by scripts/generateAudioCatalogue.mjs. Do not edit by hand.\n\nexport type AudioAssetKind = 'music' | 'sfx';\n\nexport interface AudioCatalogueEntry {\n  id: string;\n  kind: AudioAssetKind;\n  path: string;\n  relativePath: string;\n  filename: string;\n  label: string;\n  bytes: number;\n  sha256: string;\n}\n\nexport const AUDIO_CATALOGUE = [\n${body}${body ? '\n' : ''}] as const satisfies readonly AudioCatalogueEntry[];\n\nexport const MUSIC_CATALOGUE = AUDIO_CATALOGUE.filter((entry) => entry.kind === 'music');\nexport const SFX_CATALOGUE = AUDIO_CATALOGUE.filter((entry) => entry.kind === 'sfx');\n`;
}

const entries = [...(await discover('music')), ...(await discover('sfx'))].sort((left, right) =>
  left.id.localeCompare(right.id),
);

const ids = new Set();
const publicPaths = new Set();
for (const entry of entries) {
  if (ids.has(entry.id)) {
    throw new Error(`Duplicate generated audio ID: ${entry.id}`);
  }
  if (publicPaths.has(entry.path)) {
    throw new Error(`Duplicate generated audio path: ${entry.path}`);
  }
  ids.add(entry.id);
  publicPaths.add(entry.path);
}

const expected = render(entries);
if (CHECK_ONLY) {
  let current = '';
  try {
    current = await fs.readFile(OUTPUT, 'utf8');
  } catch (error) {
    if (error?.code !== 'ENOENT') {
      throw error;
    }
  }
  if (current !== expected) {
    console.error('Audio catalogue is stale. Run npm run audio:catalogue and commit the result.');
    process.exitCode = 1;
  }
} else {
  await fs.mkdir(path.dirname(OUTPUT), { recursive: true });
  await fs.writeFile(OUTPUT, expected, 'utf8');
  console.log(`Audio catalogue generated: ${entries.length} MP3 file(s).`);
}
